### ISSUE TITLE
TypeError with training

### ISSUE THREAD

**Issue by shreystechtips** [AndPuQing/ContextPrior_Paddle#1]
When running the included `python train.py` using the `paddlepaddle/paddle:2.2.0-gpu-cuda11.2-cudnn8` docker image, I receive the following error:

```
Traceback (most recent call last):
  File "train.py", line 85, in <module>
    use_vdl=True,
  File "/app/ContextPrior_Paddle/tool/train.py", line 224, in train
    edges=edges)
  File "/app/ContextPrior_Paddle/tool/train.py", line 80, in loss_computation
    loss_list.append(losses['coef'][i] * loss_i(logits.astype('float64'), labels.astype("float64")))
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/app/ContextPrior_Paddle/loss/affinityloss.py", line 32, in forward
    ideal_affinity_matrix = self._construct_ideal_affinity_matrix(label, [60, 60])
  File "/app/ContextPrior_Paddle/loss/affinityloss.py", line 20, in _construct_ideal_affinity_matrix
    scaled_labels[scaled_labels == 255] = self.num_classes
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 637, in __setitem__
    return _setitem_impl_(self, item, value)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/variable_index.py", line 583, in _setitem_impl_
    return set_value_for_bool_tensor(var, slice_item, value)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/variable_index.py", line 682, in set_value_for_bool_tensor
    "but received {}.".format(var.dtype))
TypeError: Only support float and double tensor for bool index, but received paddle.int64.
```

The error appears to come from [this line](https://github.com/AndPuQing/ContextPrior_Paddle/blob/216c5fdc0fedf736701ebf803392ae859fe4a569/loss/affinityloss.py#L19) and the following line where `scaled_labels` is set. Explicitly typecasting to `float` instead of `int64` yields an error about `squeeze_` not supporting the function. 

Thank you! Any help would be appreciated.

**Comment by AndPuQing** [comment]
> When running the included `python train.py` using the `paddlepaddle/paddle:2.2.0-gpu-cuda11.2-cudnn8` docker image, I receive the following error:
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 85, in <module>
>     use_vdl=True,
>   File "/app/ContextPrior_Paddle/tool/train.py", line 224, in train
>     edges=edges)
>   File "/app/ContextPrior_Paddle/tool/train.py", line 80, in loss_computation
>     loss_list.append(losses['coef'][i] * loss_i(logits.astype('float64'), labels.astype("float64")))
>   File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
>     outputs = self.forward(*inputs, **kwargs)
>   File "/app/ContextPrior_Paddle/loss/affinityloss.py", line 32, in forward
>     ideal_affinity_matrix = self._construct_ideal_affinity_matrix(label, [60, 60])
>   File "/app/ContextPrior_Paddle/loss/affinityloss.py", line 20, in _construct_ideal_affinity_matrix
>     scaled_labels[scaled_labels == 255] = self.num_classes
>   File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 637, in __setitem__
>     return _setitem_impl_(self, item, value)
>   File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/variable_index.py", line 583, in _setitem_impl_
>     return set_value_for_bool_tensor(var, slice_item, value)
>   File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/variable_index.py", line 682, in set_value_for_bool_tensor
>     "but received {}.".format(var.dtype))
> TypeError: Only support float and double tensor for bool index, but received paddle.int64.
> ```
> 
> The error appears to come from [this line](https://github.com/AndPuQing/ContextPrior_Paddle/blob/216c5fdc0fedf736701ebf803392ae859fe4a569/loss/affinityloss.py#L19) and the following line where `scaled_labels` is set. Explicitly typecasting to `float` instead of `int64` yields an error about `squeeze_` not supporting the function.
> 
> Thank you! Any help would be appreciated.

Hello, I just tried to write it like this
```python
a=paddle.floor(paddle.rand([5,5])*255)
print(a)
```
Tensor(shape=[5, 5], dtype=float32, place=CUDAPlace(0), stop_gradient=True,
       [[230., 150., 60. , 109., 218.],
        [37. , 75. , 243., 8.  , 18. ],
        [149., 53. , 242., 104., 212.],
        [117., 226., 105., 85. , 100.],
        [89. , 10. , 42. , 5.  , 200.]])
```python
a[a==95]=0
print(a)
```
Tensor(shape=[5, 5], dtype=float32, place=CUDAPlace(0), stop_gradient=True,
       [[230., 150., 60. , 109., 218.],
        [37. , 75. , 243., 8.  , 18. ],
        [149., 53. , 242., 104., 212.],
        [117., 226., 105., 85. , 100.],
        [89. , 10. , 42. , 5.  , 200.]])

So I think in `paddlepaddle==2.2.0` support for retrieving data of type int was removed

I suggest you write it like this, it might work

```python
scaled_labels = scaled_labels.squeeze_()
scaled_labels[scaled_labels == 255] = self.num_classes
scales_labels=scales_labels.astype('int64')
```
Hope can help you

**Comment by shreystechtips** [comment]
Thank you so much for this, it ended up working!
